name: 'Static Build'
description: 'Builds Static Websites'
branding:
  icon: 'cloud'
  color: 'gray-dark'
inputs:
  entrypoint:
    description: 'static-website-builder binary entrypoint'
    required: false
    default: '/gympass/static-website-builder'
  confirm:
    description: 'whether the action should request confirmation before continuing'
    required: false
    default: false
  env:
    description: 'Environment name to build'
    required: true
  deploy-to:
    description: 'Target environment to deploy to'
    required: true
  load-envs-from:
    description: 'Filename to load containing environment variables'
    required: false
  preserve-build-directory:
    description: 'Retains the build directory; otherwise, the build directory is removed after the deploy is complete'
    required: false
    default: false
outputs:
  deployed-to-production:
    description: "Whether the action deployed changes to production. Possible values are 'true' and 'false'"
    value: ${{ steps.build.outputs.TO_PRODUCTION }}
runs:
  using: "composite"
  steps:
    - name: "Build image"
      id: build
      shell: bash
      run: |
        set -eux
        cmd=("${{ inputs.entrypoint }}" --env ${{ inputs.env }});
        if [ -n '${{ inputs.load-envs-from }}' ]; then cmd+=(--load-envs-from ${{ inputs.load-envs-from }}); fi
        "${cmd[@]}";

        if [[ '${{ inputs.confirm }}' == 'true' ]]; then
          if ! /gympass/confirm --github-token "${{ github.token }}" --exit-code; then
            echo '::set-output name=TO_PRODUCTION::false'
            echo "Aborted.";
            exit 0;
          fi
        fi

        set +a
        source /tmp/static-build-envs
        set -a

        /gympass/cloudfront-deploy --environment '${{ inputs.deploy-to }}' \
                                   --bucket-name "$BUCKET_NAME" \
                                   --cloudfront-id "$CLOUDFRONT_ID" \
                                   --source 'build/'

        if [[ '${{ inputs.preserve-build-directory }}' == 'false' ]]; then
          rm -rf build/
        fi

        echo '::set-output name=TO_PRODUCTION::true'
