name: 'Static Build'
description: 'Builds Static Websites'
branding:
  icon: 'cloud'
  color: 'gray-dark'
inputs:
  entrypoint:
    description: 'static-website-builder binary entrypoint'
    required: false
    default: '/gympass/static-website-builder'
  confirm:
    description: 'whether the action should request confirmation before continuing'
    required: false
    default: false
  env:
    description: 'Environment name to build'
    required: true
  deploy-to:
    description: 'Target environment to deploy to'
    required: true
  load-envs-from:
    description: 'Filename to load containing environment variables'
    required: false
  preserve-build-directory:
    description: 'Retains the build directory; otherwise, the build directory is removed after the deploy is complete'
    required: false
    default: false
  working-directory:
    description: 'Alternative working directory to run this action from'
    required: false
  extra-envs:
    description: 'List of extra environment variables composed of one or more lines in the format KEY=VALUE'
    required: false
  build-command:
    description: 'Overrides the default "build" command passed to yarn'
    required: false
  deploy-source:
    description: 'Source directory containing output files to be pushed to S3'
    required: false
outputs:
  deployed-to-production:
    description: "Whether the action deployed changes to production. Possible values are 'true' and 'false'"
    value: ${{ steps.build.outputs.TO_PRODUCTION }}
runs:
  using: "composite"
  steps:
    - id: build
      shell: bash
      env:
        EXTRA_ENVS: ${{ inputs.extra-envs }}
      run: |
        set -eux
        cmd=("${{ inputs.entrypoint }}" --env ${{ inputs.env }});
        if [ -n '${{ inputs.load-envs-from }}' ]; then cmd+=(--load-envs-from '${{ inputs.load-envs-from }}'); fi
        if [ -n '${{ inputs.working-directory }}' ]; then cmd+=(--working-directory '${{ inputs.working-directory }}'); fi
        if [ -n '${{ inputs.build-command }}' ]; then cmd+=(--build-command '${{ inputs.build-command }}'); fi
        if [[ -n "${EXTRA_ENVS:+x}" ]]; then
          cat <<-EOF > /tmp/static-build-extra-envs
            ${EXTRA_ENVS}
        EOF
          cmd+=(--extra-envs-from /tmp/static-build-extra-envs);
        fi

        "${cmd[@]}";

        if [[ '${{ inputs.confirm }}' == 'true' ]]; then
          if ! /gympass/confirm --github-token "${{ github.token }}" --exit-code; then
            echo '::set-output name=TO_PRODUCTION::false'
            echo "Aborted.";
            exit 0;
          fi
        fi

        set +a
        source /tmp/static-build-envs
        set -a

        deploy=('/gympass/cloudfront-deploy'
                '--environment' '${{ inputs.deploy-to }}'
                '--bucket-name' "$BUCKET_NAME"
                '--cloudfront-id' "$CLOUDFRONT_ID")

        if [ -n '${{ inputs.deploy-source }}' ]; then
          sourceName="$(basename "${{ inputs.deploy-source }}")"
          workingDir="$(dirname "${{ inputs.deploy-source }}")"

          deploy+=('--working-directory' "${workingDir}"
                   '--source' "${sourceName}");
        else if [ -n '${{ inputs.working-directory }}' ]; then
          deploy+=(--working-directory ${{ inputs.working-directory }});
          deploy+=('--source' 'build/')
        else
          deploy+=('--source' 'build/')
        fi
        "${deploy[@]}"

        if [[ '${{ inputs.preserve-build-directory }}' == 'false' ]]; then
          if [[ -n '${{ inputs.deploy-source }}' ]]; then
            rm -rf '${{ inputs.deploy-source }}'
          else if [[ -n '${{ inputs.working-directory }}' ]]; then
            rm -rf '${{ inputs.working-directory }}/build'
          else
            rm -rf build
          fi
        fi

        echo '::set-output name=TO_PRODUCTION::true'
